In [25]:
import numpy as np

In [3]:
# numpy  indexing and slicing of vectors

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[1:5]

array([12, 13, 14, 15])

In [6]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [9]:
arr[3::2]     

array([14, 16, 18, 20])

In [10]:
# here in this part we can steps 

In [13]:
arr[0:11:2]

array([11, 13, 15, 17, 19])

In [ ]:
# numpy indexing and slicing of matrix

In [14]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[5]

array([26, 27, 28, 29, 30])

In [16]:
arr[0,0]

1

In [17]:
arr[3]

array([16, 17, 18, 19, 20])

In [18]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [19]:
arr[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
arr[:6]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[1:6:2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])

In [ ]:
# bollean indexing

In [32]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [34]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])