In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
a=[1,2,34,2.3,"dkdh"]
a

[1, 2, 34, 2.3, 'dkdh']

In [7]:
np.array(a)

array(['1', '2', '34', '2.3', 'dkdh'], dtype='<U32')

In [8]:
l = [[1,2,3],[4,5,6],[12,23,34]]
l

[[1, 2, 3], [4, 5, 6], [12, 23, 34]]

In [9]:
np.array(l)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 23, 34]])

In [16]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [17]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [21]:
np.random.rand(10)

array([0.56804824, 0.7594024 , 0.96081777, 0.37411657, 0.21975171,
       0.05427912, 0.59254024, 0.52086884, 0.42317572, 0.1392965 ])

this the example of random num generation

In [24]:
np.random.randint(5)

0

In [25]:
np.random.randint(1,10,2)

array([7, 3])