In [56]:
import numpy as np

In [57]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [58]:
a=[1,2,34,2.3,"dkdh"]
a

[1, 2, 34, 2.3, 'dkdh']

In [59]:
np.array(a)

array(['1', '2', '34', '2.3', 'dkdh'], dtype='<U32')

In [60]:
l = [[1,2,3],[4,5,6],[12,23,34]]
l

[[1, 2, 3], [4, 5, 6], [12, 23, 34]]

In [61]:
np.array(l)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 23, 34]])

In [62]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [63]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [64]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [66]:
np.random.rand(10)

array([0.67531647, 0.32373422, 0.13849141, 0.91796475, 0.43762194,
       0.72400281, 0.76115281, 0.43315538, 0.0336921 , 0.00156213])

this the example of random num generation

In [67]:
np.random.randint(5)

3

In [68]:
np.random.randint(1,10,2)

array([6, 1])

In [69]:
# array attrbutes

In [70]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr.shape

(3, 3)

In [72]:
arr.size

9

In [73]:
arr.dtype

dtype('int32')

In [74]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr.min

<function ndarray.min>

In [76]:
arr.min()

1

In [77]:
arr.mean()

5.0

In [79]:
arr.max()

30

In [80]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [82]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])